<?php

/* MySQL DATABASE CONFIGURATION */

define("MYSQL_DBHOST", "MY_MYSQL_DBHOST");
define("MYSQL_DBNAME", "MY_MYSQL_DBNAME");
define("MYSQL_USER", "MY_MYSQL_USER");
define("MYSQL_PASS", "MY_MYSQL_PASS");

 
?>
